# Generated by Django 2.2.3 on 2019-09-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0002_old_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='old',
        ),
    ]
