# Generated by Django 2.2.3 on 2019-09-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0004_auto_20190928_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
