# Generated by Django 2.2.3 on 2019-09-28 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0005_auto_20190928_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='agent',
        ),
    ]
