# Generated by Django 2.2.3 on 2019-09-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0007_auto_20190928_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='booked',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Yes')], default=1),
        ),
    ]
