# Generated by Django 2.2.3 on 2019-09-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0009_auto_20190928_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='booked',
            field=models.IntegerField(),
        ),
    ]
